[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.265.779 [stars_engine.cc:1540]392315 ProcLogicCqReport:[INIT][DEFAULT]Task run failed, device_id=8, stream_id=2, task_id=50073, sqe_type=3(place holder), errType=0x20(sq sw status error), sqSwStatus=0x105
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.267.167 [device_error_proc.cc:1321]392315 PrintStreamTimeoutSnapshotInfo:[INIT][DEFAULT]stream_id=8, task_id=49318, taskType=66 (KERNEL_AIVEC).
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.267.416 [device_error_proc.cc:1415]392315 ProcessStarsWaitTimeoutErrorInfo:[INIT][DEFAULT]report error module_type=6, module_name=EE9999
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.267.421 [device_error_proc.cc:1415]392315 ProcessStarsWaitTimeoutErrorInfo:[INIT][DEFAULT]The error from device(chipId:4, dieId:0), serial number is 14, event wait timeout occurred during task execution, stream_id:2, sq_id:2, task_id:50073, event_id=2298, timeout=150s.
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.267.532 [stream.cc:3278]392315 EnterFailureAbort:[INIT][DEFAULT]stream_id=2 enter failure abort.
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.534 [event_task.cc:535]392315 DoCompleteSuccessForEventWaitTask:[INIT][DEFAULT]event wait error, retCode=0x105, [task timeout].
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.540 [stream.cc:1180]392315 GetError:[INIT][DEFAULT]Stream Synchronize failed, stream_id=2, retCode=0x105, [task timeout].
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.554 [event_task.cc:607]392315 PrintErrorInfoForEventWaitTask:[INIT][DEFAULT]Task execute failed, device_id=8, stream_id=2, task_id=50073, flip_num=11, task_type=3(EVENT_WAIT), event_flag=0x1. 
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.582 [stars_engine.cc:1410]392315 StarsResumeRtsq:[INIT][DEFAULT]stop scheduling in abort failure mode: stream_id=2, sq_id=2, sq_head=910, task_id=50073, taskType=3.
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.588 [stars_engine.cc:1155]392315 SyncTask:[INIT][DEFAULT]stream is in failure abort and need to reclaim all, device_id=8, stream_id=2.
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.602 [stream.cc:1180]392315 GetError:[INIT][DEFAULT]Stream Synchronize failed, stream_id=2, retCode=0x105, [task timeout].
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.605 [stream.cc:1183]392315 GetError:[INIT][DEFAULT]report error module_type=2, module_name=EI9999
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.607 [stream.cc:1183]392315 GetError:[INIT][DEFAULT]Task execute failed, device_id=8, stream_id=2, task_id=50073, flip_num=11, task_type=3(EVENT_WAIT), event_flag=0x1. 
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.644 [api_error.cc:973]392315 StreamSynchronize:[INIT][DEFAULT]Stream synchronize failed, stream_id=2, timeout=-1ms.
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.667 [api_c_stream.cc:173]392315 rtStreamSynchronizeWithTimeout:[INIT][DEFAULT]ErrCode=107020, desc=[task timeout], InnerCode=0x7150059
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.672 [error_message_manage.cc:53]392315 FuncErrorReason:[INIT][DEFAULT]report error module_type=3, module_name=EE8888
[ERROR] RUNTIME(392315,python):2025-10-24-20:20:31.272.676 [error_message_manage.cc:53]392315 FuncErrorReason:[INIT][DEFAULT]rtStreamSynchronizeWithTimeout execute failed, reason=[task timeout]
